project:
  type: website

website:
  title: "Example docs for UKFE"
  description: "Training materials"
  repo-url: https://matthew-stapleton-jba.github.io/ukfe-docs-review/
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
      - section: Subsection
        contents:
          - sub_section/subsection.qmd

theme:
  light: cosmo
  dark: darkly
